task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64

  name: "release-vs-ponyc-release-freebsd-12"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash gmake git
    - bash .ci-scripts/freebsd-12.1-install-pony-tools.bash

  test_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:$PATH"
    - gmake test config=release

task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64

  name: "debug-vs-ponyc-release-freebsd-12"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash gmake git
    - bash .ci-scripts/freebsd-12.1-install-pony-tools.bash

  test_script:
    - export PATH="/tmp/corral/bin:/tmp/ponyc/bin/:$PATH"
    - gmake test config=debug
