name: PR

on: pull_request

jobs:
  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  release-vs-ponyc-release:
    name: Verify release mode on Linux with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Test with the most recent ponyc release
        run: make test config=release

  debug-vs-ponyc-release:
    name: Verify debug mode on Linux with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Test with the most recent ponyc release
        run: make test config=debug

  macos-debug-vs-ponyc-release:
    name: Verify PR builds on macOS with most recent ponyc release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install pony tools
        run: bash .ci-scripts/macOS-install-release-pony-tools.bash
      - name: Test with the most recent ponyc release
        run: |
          export PATH=/Users/runner/.local/share/ponyup/bin/:$PATH
          make test config=debug

  macos-release-vs-ponyc-release:
    name: Verify PR builds on macOS with most recent ponyc release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install pony tools
        run: bash .ci-scripts/macOS-install-release-pony-tools.bash
      - name: Test with the most recent ponyc release
        run: |
          export PATH=/Users/runner/.local/share/ponyup/bin/:$PATH
          make test config=release
