name: PR

on: pull_request

jobs:
  release-vs-ponyc-release:
    name: Verify release mode on Linux with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Test with the most recent ponyc release
        run: make test config=release

  debug-vs-ponyc-release:
    name: Verify debug mode on Linux with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Test with the most recent ponyc release
        run: make test config=debug
