name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@0.5.0
        with:
          step: trigger-release-announcement
          git_user_name: "Sean T. Allen"
          git_user_email: "sean@seantallen.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
