name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  update-version-in-readme-examples:
    runs-on: ubuntu-latest
    name: Update version in README examples
    steps:
      - name: Update version in README examples
        uses: docker://ponylang/readme-version-updater-action:0.3.1
        with:
          git_user_name: "Sean T. Allen"
          git_user_email: "sean@seantallen.com"
        env:
          API_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs:
      - update-version-in-readme-examples
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: docker://ponylang/release-bot-action:0.5.0
        with:
          step: trigger-release-announcement
          git_user_name: "Sean T. Allen"
          git_user_email: "sean@seantallen.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
